#! /bin/sh

# This script will go through and install 'threshold' on the local machine. Please see license agreement before continuing https://raw.githubusercontent.com/secureoptions/threshold/master/LICENSE

if [ $(id -u) -ne 0 ]
then 
	echo ""
	echo "Permission denied (must be superuser)"
	echo ""
    exit
fi
echo "Installing... "

mkdir /etc/threshold/
mkdir /etc/threshold/pids/
mkdir /etc/threshold/triggers/
mkdir /etc/threshold/actions/

curl -O /usr/bin/threshold https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.sh >> /dev/null 
chmod 755 /usr/bin/threshold

curl -O /usr/share/man/man1/threshold.1 https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.1.man >> /dev/null
gzip /usr/share/man/man1/threshold.1 >> /dev/null

echo ""
echo "Done!"
echo "Use \"man threshold\" for usage details"

rm -- $0
