#! /bin/sh

# This script will go through and install 'threshold' on the local machine. Please see license agreement before continuing https://raw.githubusercontent.com/secureoptions/threshold/master/LICENSE

if [ $(id -u) -ne 0 ]
then 
	echo ""
	echo "Permission denied (must be superuser)"
	echo ""
    exit
fi
echo "Installing..."

mkdir /etc/threshold/
mkdir /etc/threshold/pids/
mkdir /etc/threshold/triggers/
mkdir /etc/threshold/actions/

wget -O /usr/bin/threshold https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.bash > /dev/null
chmod 755 /usr/bin/threshold

wget -O /usr/share/man/man1/threshold.1 https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.1 > /dev/null
gzip /usr/share/man/man1/threshold.1

echo ""
echo "Done!"
echo "Use \"man threshold\" for usage details"
