#! /bin/sh

# This script will go through and install 'threshold' on the local machine. Please see license agreement before continuing https://raw.githubusercontent.com/secureoptions/threshold/master/LICENSE

if [ $(id -u) -ne 0 ]
then 
	echo ""
	echo "Permission denied (must be superuser)"
	echo ""
    exit
fi

LATEST="v2.1"

uninstall()
{
	answer=${answer:-N}
	answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
	if [ "$answer" = "y" ]
	then 	
		echo "Cleaning up any running jobs..."
		killall threshold > /dev/null 2>&1
        	echo "Uninstalling threshold..." > /dev/tty
		rm -Rf /etc/threshold/
		rm -f /usr/share/man/man1/threshold.1.gz
		rm -f /usr/bin/threshold
		echo "Done!" > /dev/tty
	else
		exit 0
	fi
}

install()
{
	echo "" > /dev/tty
	echo "Installing threshold ${LATEST}... " > /dev/tty
	
	mkdir /etc/threshold/
	mkdir /etc/threshold/triggers/
	mkdir /etc/threshold/actions/


	# Check if device is a Mac or *nix
	sw_vers > /dev/null
	result=$?

	if [ $result -eq 0 ]
	then
	   curl -o /usr/local/bin/threshold https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.sh 
	   chmod 755 /usr/local/bin/threshold
	else 
	   curl -o /usr/bin/threshold https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.sh
	   chmod 755 /usr/bin/threshold
	 fi


	curl -o /usr/share/man/man1/threshold.1 https://raw.githubusercontent.com/secureoptions/threshold/master/threshold.1.man
	gzip /usr/share/man/man1/threshold.1
	
	echo "Done!" > /dev/tty
	echo "Use \"man threshold\" for usage details" > /dev/tty


	rm -- $0
} 



# check if there is any other older installation
threshold -v > /dev/null 2>&1
RESULT=$?
if [ "$RESULT" -ne 0 ]
then
	install > /dev/null 2>&1
	exit 0
else
	VERSION=$(threshold -v)
fi
	

# If there is a pre-existing version, check version and prompt to reinstall
if [ "$VERSION" == "$LATEST" ]
then 
	echo "It looks like you are already on the latest version (${VERSION}).\nDo you want to reinstall threshold again with this same version (N/y)?"
	read -r "" answer
	answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
	if [ "$answer" = "y" ]
	then
		uninstall > /dev/null 2>&1
		install > /dev/null 2>&1
	else
		echo "Exiting installation, nothing to do"
		exit 0
	fi
	
else
	echo "It looks like you have an older version (${VERSION}) which\nneeds to be uninstalled before installing the later version, $LATEST."
	read -r "Do you wish to proceed (N/y)? "  answer
	answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
	if [ "$answer" = "y" ]
	then
		uninstall > /dev/null 2>&1
		install > /dev/null 2>&1
	else
		echo "Exiting installation, nothing to do"
		exit 0
	fi
fi







